### ISSUE TITLE
[2pts] Group task #1 - Create an Item Class #1

### ISSUE THREAD

**Issue by hafiz1379** [hafiz1379/Catalog-of-my-things#1]
Create an `Item` class in a separate .rb file.

 All `Item` class properties visible in the diagram should be defined and set up in the constructor method.

**Exception: Properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.**

**Comment by Lucas-Masaba** [comment]
# Hello @JuanDiegoGuerra @Rysth @hafiz1379  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 
- [ ] Your GitHub issue description should have the following info:
  - link to their GitHub project
  - information about the number of people in their group
  - list of GitHub usernames assigned to: Team member 1, Team member 2, Team member 3

- [ ] Please do not share a closed issue for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
